### ISSUE TITLE
Finish Roboticon Testing

### ISSUE THREAD

**Issue by Mart500** [RobinStephenson/jbt#39] opened 2017-01-15 20:35 UTC
Finish testing for roboticon, roboticon customisation and market classes.

**Comment by Mart500** [comment] 2017-01-16 21:21
Updated all roboticon testing, will continue to do so when Tile is merged completely.

**Comment by Mart500** [comment] 2017-01-18 09:41
Roboticon, Roboticon customisation and the updated market class have all had their testing updated.

**Comment by RobinStephenson** [comment] 2017-01-18 17:54
@Mart500 reopening as the issue isnt solved until the pull request with the fix is merged. close this again by referencing the issue number when merging the pull request

**Comment by RobinStephenson** [comment] 2017-01-20 18:47
#52

**Closed as completed by RobinStephenson** 2017-01-20 18:47 UTC
Labels: duplicate, feature, easy-pickings
